name: publish

on:
  push:
    tags:
      - v*
        
jobs:

  readyGo:

    runs-on: ubuntu-latest

    container:
      image: node:12.14.0

    env: 
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      PUBLISH_OPTS: ${{ github.ref_name == 'master' && '--verbose' || '--verbose --tag=alpha' }}

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: get version from package.json
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version
          
      - name: before scripts
        run: |
          echo "Current branch: ${{ github.ref_name }}"
          echo "Current publish version: ${{ env.VERSION }}"
        env:
          VERSION: ${{ steps.version.outputs.value }}

      - name: install packages
        run: |
          npm ci

      - name: build
        run: |
          npm run build
      
      - name: publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm publish $PUBLISH_OPTS --access public
          echo "记得同步 taobao 源哦： https://npm.taobao.org/sync/authing-wxapp-sdk  🚀"
